swipe:
  3:
    #right:
      #command: "swaymsg 'workspace next'"
    #left:
      #command: "swaymsg 'workspace prev'"
    right:
      command: "i3-msg 'workspace next'"
    left:
      command: "i3-msg 'workspace prev'"
    up:
      command: "python3 ~/.config/fusuma/empty.py &"

threshold:
  swipe: 1

interval:
  swipe: 1
